#set up properties
server:
    port: ${SERVER_PORT:8080}

management:
    security:
        enabled: false
    endpoint:
        restart:
            enabled: true

spring:
    profiles:
        active: mysql, dev
    data:
        rest: 
            base-path: /api
    application:
        name: standalone
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DATABASE_HOST:104.198.233.3}:${DATABASE_PORT:3306}/${DATABASE_NAME:marketplace}?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
        password: ${RDS_PASSWORD:tpm1234}
        username: ${RDS_USERNAME:root}
        schema: classpath:/schema.sql
        initialization-mode: always
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect